#
# Vagrantfile for curate_nd
#
#
Vagrant.configure(2) do |config|
  
# Where the clone of git.library.nd.edu:puppet_standalone lives on your box
#
PUPPET_REPO_PATH=ENV['PUPPET_REPO_PATH']

# Use CentOS image w/puppet already installed

  config.vm.box = "nrel/CentOS-6.5-x86_64"
  config.vm.hostname = "bendo-devl-vm.library.nd.edu"

  # Disable automatic box update checking. 
  config.vm.box_check_update = false

  # Create a private network ip
  config.vm.network "private_network", ip: "192.168.50.3"

  # root folder shared as /vagrant. Share hiera as well 
  config.vm.synced_folder "../puppet/hiera", "/var/lib/hiera"

  # Provider-specific configuration
  #
   config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
	vb.memory = "4096"
	vb.cpus = 2
        vb.name = "bendo-devl-vm"
   end

  # CentOS provisioning
  config.vm.provision "shell", inline: "yum list rpmforge-release || yum -y install http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm"
  config.vm.provision "shell", inline: "yum list epel-release || yum -y install epel-release"
  config.vm.provision "shell", inline: "cp -f /vagrant/iptables /etc/sysconfig/iptables && service iptables restart"
  config.vm.provision "shell", inline: "puppet module install --force  puppetlabs/vcsrepo"

  #m Enable provisioning with Puppet
  # 
  config.vm.provision :puppet do |puppet|
       puppet.manifests_path     = "../puppet/manifests"
       puppet.manifest_file     = "vagrant.pp"
       puppet.hiera_config_path = "../puppet/hiera.yaml"
       puppet.module_path = [  "#{PUPPET_REPO_PATH}/modules" , "../puppet/modules" ]
       puppet.options = "--verbose "
  end

  config.vm.provision "shell", inline: "usermod -G app nginx"
end
